# Generated by Django 2.1.1 on 2018-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateField(null=True),
        ),
    ]
